# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "rdoc", "~>6.1.2.1", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

